---
title: "Homework 5 Exercise 2"
author: "Miranda Law"
date: "2026-01-21"
output: html_document
---

# Start fresh
```{r start-fresh}
# clear the memory of the working environment at the start of the session
rm(list = ls())
```

# Install and load packages

```{r packages}
# install the rio package if necessary
# install.packages('rio')

# install the ggplot2 package if necessary
# install.packages('ggplot2')

# install the dplyr package if necessary
# install.packages('dplyr')


# load the rio package into session
library(rio)

# load the ggplot2 package into session
library(ggplot2)

# load the dplyr package into session
library(dplyr)
```

# Read in data
```{r load-data}
# get GitHub URL for data
dataURL = "https://github.com/DACSS-601-Data-Science-Fundamentals/hw5-exercise2/raw/refs/heads/main/HDR25_Statistical_Annex_HDI_Table.xlsx"

# read in data
data = import(dataURL)
```
# Data cleaning

## First observations
```{r check-data}
# take a look at the data
str(data)

# check beginning of the data
head(data)

# check end of the data
tail(data)
```

At a first glance, there column names messy, and there are essentially empty columns and rows. At the end of there are notes about the data. Additionally, all values are characters.

## Cleaning
```{r clean-data, message=FALSE}
# filter for data where the actual HDI rank column is not empty
data = data |> filter(!is.na(...1))

# check data
str(data)

# select columns
data = data |> 
  select(...1,
         `Table 1. Human Development Index and its components`,
         ...3,
         ...5,
         ...7,
         ...9,
         ...11,
         ...13,
         ...15)

# check data
str(data)

# rename columns
names(data) = c("HDI_Rank2023", "Country", "HDI", "Life_expectancy_at_birth", "Expected_years_of_schooling", "Mean_years_of_schooling", "GNI_per_capita", "GNI_per_capita_rank_minus_HDI_rank", "HDI_Rank2022")

# check names
names(data)

# check beginning of data
head(data)

# drop first row
data = data[-1,]

# check beginning of data again
head(data)

# convert all values to numeric
data = mutate(data, across(-c("Country"), as.numeric))

# check class of each column
lapply(data, class)
```

# Summarize data
```{r means, warning=FALSE}
# calculate mean for Life_expectancy_at_birth
mean(data$Life_expectancy_at_birth)

# calculate mean for Expected_years_of_schooling
mean(data$Expected_years_of_schooling)

# calculate mean for Mean_years_of_schooling
mean(data$Mean_years_of_schooling)

# calculate mean for GNI_per_capita
mean(data$GNI_per_capita)
```
# Save data
```{r save-data}
# save the cleaned data as a CSV file
write.csv(data,"cleanedData.csv", row.names=FALSE)

# read in the saved CSV file for aggregated data by Region
cleanedData_CSV = read.csv("cleanedData.csv")

# explore the contents of cleaned_CSV
str(cleanedData_CSV)
```



